<?php

namespace LineMob\KeywordBundle\Model;

use PhpMob\MediaBundle\Model\Image;

class ReplyImageMessagePicture extends Image
{
    public function getBasePath()
    {
        return parent::getBasePath(); // TODO: Change the autogenerated stub
    }
}
