phpmob_media:
    filters:
        reply_image_picture:
            - { code: reply_image_picture, label: reply_image_picture, filter: ~ }

liip_imagine:
    filter_sets:
        reply_message_image_preview:
            quality: 70
            filters:
                thumbnail: { size : [300, 200], mode : inset }
